CREATE OR REPLACE PROCEDURE IS_SENIOR_EMPLOYEE IS
JDATE DATE ;
YEARS NUMBER ;
BEGIN
SELECT HIRE_DATE INTO JDATE
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 100 ;
YEARS := (MONTHS_BETWEEN(SYSDATE, JDATE) / 12) ;
IF YEARS >= 10 THEN
DBMS_OUTPUT.PUT_LINE('The employee worked 10 years or more') ;
ELSE
DBMS_OUTPUT.PUT_LINE('The employee worked less than 10 years') ;
END IF ;
END ;
/

EXECUTE IS_SENIOR_EMPLOYEE;

DECLARE
BEGIN
IS_SENIOR_EMPLOYEE ;
END ;


--procedure and function can take inputs

CREATE OR REPLACE PROCEDURE IS_SENIOR_EMPLOYEE_NEW(EID IN VARCHAR2) IS
JDATE DATE ;
YEARS NUMBER ;
BEGIN
SELECT HIRE_DATE INTO JDATE
FROM EMPLOYEES
WHERE EMPLOYEE_ID = EID ;
YEARS := (MONTHS_BETWEEN(SYSDATE, JDATE) / 12) ;
IF YEARS >= 10 THEN
DBMS_OUTPUT.PUT_LINE('The employee '||EID||' worked 10 years or more') ;
ELSE
DBMS_OUTPUT.PUT_LINE('The employee worked less than 10 years') ;
END IF ;
END ;
/

EXECUTE IS_SENIOR_EMPLOYEE_NEW(102);
EXECUTE IS_SENIOR_EMPLOYEE_NEW(105);



--taking output
CREATE OR REPLACE PROCEDURE IS_SENIOR_EMPLOYEE(EID IN VARCHAR2, MSG OUT VARCHAR2)
IS
JDATE DATE ;
YEARS NUMBER ;
BEGIN
SELECT HIRE_DATE INTO JDATE
FROM EMPLOYEES
WHERE EMPLOYEE_ID = EID ;
YEARS := (MONTHS_BETWEEN(SYSDATE, JDATE) / 12) ;
IF YEARS >= 10 THEN
MSG := 'The employee worked 10 years or more' ;
ELSE
MSG := 'The employee worked less than 10 years' ;
END IF ;
EXCEPTION
WHEN NO_DATA_FOUND THEN
MSG := 'No employee found.' ;
WHEN TOO_MANY_ROWS THEN
MSG := 'More than one employee found.' ;
WHEN OTHERS THEN
MSG := 'Some unknown error occurred.' ;
END;
/

DECLARE
MESSAGE VARCHAR2(100) ;
BEGIN
 IS_SENIOR_EMPLOYEE(105,message);
DBMS_OUTPUT.PUT_LINE(MESSAGE);
END;



---functions

CREATE OR REPLACE FUNCTION GET_SENIOR_EMPLOYEE(EID IN VARCHAR2)
RETURN VARCHAR2 IS
JDATE DATE ;
YEARS NUMBER ;
MSG VARCHAR2(100) ;
BEGIN
SELECT HIRE_DATE INTO JDATE
FROM EMPLOYEES
WHERE EMPLOYEE_ID = EID ;
YEARS := (MONTHS_BETWEEN(SYSDATE, JDATE) / 12) ;
IF YEARS >= 20 THEN
MSG := 'The employee worked 20 years or more' ;
ELSE
MSG := 'The employee worked less than 20 years' ;
END IF ;
RETURN MSG ; --return the message
EXCEPTION
--you must return value from this section also
WHEN NO_DATA_FOUND THEN
RETURN 'No employee found.' ;
WHEN TOO_MANY_ROWS THEN
RETURN 'More than one employee found.' ;
WHEN OTHERS THEN
RETURN 'Some unknown error occurred.' ;
END ;
/

DECLARE
message varchar2(100);
begin:
message:=GET_SENIOR_EMPLOYEE(100000);
DBMS_OUTPUT.PUT_LINE(message);
message:=GET_SENIOR_EMPLOYEE(104);
DBMS_OUTPUT.PUT_LINE(message);
end;

select last_name,GET_SENIOR_EMPLOYEE(EMPLOYEE_ID)
from employees;



--nested

CREATE OR REPLACE FUNCTION GET_SENIOR_EMPLOYEE(EID IN VARCHAR2)
RETURN VARCHAR2 IS
ECOUNT NUMBER;
JDATE DATE ;
YEARS NUMBER ;
MSG VARCHAR2(100) ;
BEGIN
    
BEGIN
SELECT COUNT(*) INTO ECOUNT
FROM EMPLOYEES
WHERE EMPLOYEE_ID = EID ;
END ;
IF ECOUNT = 0 THEN
MSG := 'No employee found.' ;
ELSIF ECOUNT > 1 THEN
MSG := 'More than one employee found.' ;
ELSE
SELECT HIRE_DATE INTO JDATE
FROM EMPLOYEES
WHERE EMPLOYEE_ID = EID ;
YEARS := (MONTHS_BETWEEN(SYSDATE, JDATE) / 12) ;
IF YEARS >= 10 THEN
MSG := 'The employee worked 10 years or more' ;
ELSE
MSG := 'The employee worked less than 10 years' ;
END IF ;
END IF ;
RETURN MSG ;
END ;
/    