DROP TABLE TEMP_EMPLOYEES;
CREATE TABLE TEMP_EMPLOYEES (
EMPLOYEE_ID VARCHAR2(10),
NAME VARCHAR2(100),
EMAIL VARCHAR2(50),
MANAGER_ID NUMBER(4,0),
MANAGER_CRED VARCHAR2(20)
);

INSERT INTO TEMP_EMPLOYEES (EMPLOYEE_ID, NAME, EMAIL, MANAGER_ID)
SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME, EMAIL, MANAGER_ID
FROM EMPLOYEES;

SELECT * FROM TEMP_EMPLOYEES;


CREATE OR REPLACE PROCEDURE POPULATE_CREDS(MIN_EMP_COUNT IN NUMBER, MIN_JOB_COUNT IN NUMBER) IS

JOB_COUNT NUMBER;
S_COUNT NUMBER;
BEGIN
    FOR R IN (SELECT EMPLOYEE_ID,EMAIL FROM EMPLOYEES  WHERE 1<= (
        SELECT COUNT(*) FROM EMPLOYEES E WHERE E.MANAGER_ID=EMPLOYEE_ID
    ) )
    LOOP
        SELECT COUNT(J.JOB_ID)+1 INTO JOB_COUNT FROM JOB_HISTORY J WHERE J.EMPLOYEE_ID=R.EMPLOYEE_ID;
        SELECT COUNT(*) INTO S_COUNT FROM EMPLOYEES E WHERE E.MANAGER_ID=R.EMPLOYEE_ID;
        IF(JOB_COUNT>=MIN_JOB_COUNT) 
        THEN UPDATE TEMP_EMPLOYEES SET MANAGER_CRED= SUBSTR(R.EMAIL,1,2)||'**'||SUBSTR(R.EMAIL,-2,2)||'-'||S_COUNT WHERE EMPLOYEE_ID=R.EMPLOYEE_ID;
        DBMS_OUTPUT.PUT_LINE('UPDATED');
        ELSIF(JOB_COUNT<MIN_JOB_COUNT AND S_COUNT>=MIN_EMP_COUNT) THEN
         UPDATE TEMP_EMPLOYEES SET MANAGER_CRED= SUBSTR(R.EMAIL,1,2)||'**'||SUBSTR(R.EMAIL,-2,2)||'-'||S_COUNT  WHERE EMPLOYEE_ID=R.EMPLOYEE_ID;
         DBMS_OUTPUT.PUT_LINE('UPDATED');
        END IF;
    END LOOP;
    END;
    /

EXECUTE POPULATE_CREDS(2,1);

SELECT * FROM TEMP_EMPLOYEES;

CREATE TABLE DEPARTMENT_JOB_MAP_TABLE AS
SELECT DISTINCT JOB_ID, DEPARTMENT_ID FROM EMPLOYEES WHERE
DEPARTMENT_ID IS NOT NULL order by DEPARTMENT_ID;

SELECT * FROM DEPARTMENT_JOB_MAP_TABLE;



DROP TABLE TEMP_EMPLOYEES;
CREATE TABLE TEMP_EMPLOYEES AS SELECT * FROM EMPLOYEES;
SELECT * FROM TEMP_EMPLOYEES;


CREATE OR REPLACE TRIGGER JOB_CHANGE BEFORE UPDATE OF JOB_ID ON TEMP_EMPLOYEES
FOR EACH ROW
DECLARE
CURRENT_MAX_SAL NUMBER;
UPDATE_MAX_SAL NUMBER;
YEARS_WORKED NUMBER;
NEW_DEPT_ID NUMBER;
BEGIN
SELECT MAX(SALARY) INTO CURRENT_MAX_SAL FROM EMPLOYEES WHERE JOB_ID = :OLD.JOB_ID;
SELECT MAX(SALARY) INTO UPDATE_MAX_SAL FROM EMPLOYEES WHERE JOB_ID = :NEW.JOB_ID;
    YEARS_WORKED:=MONTHS_BETWEEN(SYSDATE,:OLD.HIRE_DATE)/12;
    IF(UPDATE_MAX_SAL<CURRENT_MAX_SAL AND YEARS_WORKED>5) THEN RAISE_APPLICATION_ERROR(-20001, 'NOT APPROVED');
    END IF;
    SELECT DEPARTMENT_ID INTO NEW_DEPT_ID FROM DEPARTMENT_JOB_MAP_TABLE WHERE JOB_ID=:NEW.JOB_ID;
    :NEW.DEPARTMENT_ID:=NEW_DEPT_ID;
END;
/

--UPDATE JOB_ID
UPDATE TEMP_EMPLOYEES
SET JOB_ID = 'MK_MAN'
WHERE EMPLOYEE_ID = 198;

SELECT * FROM TEMP_EMPLOYEES;